apiVersion: v1
kind: Service
metadata:
  name: chercheur-service
spec:
  type: LoadBalancer
  selector:
    app: chercheur-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
