apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projet-service
  template:
    metadata:
      labels:
        app: projet-service
    spec:
      containers:
        - name: projet-container
          image: chkhonty9/projet-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://discovery-service:8761/eureka"
            - name: CONFIG_SERVICE_URL
              value: "http://config-service:9999"
