apiVersion: v1
kind: Service
metadata:
  name: enseignant-service
spec:
  type: LoadBalancer
  selector:
    app: enseignant-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
